name: Test
on:
  push:
jobs:
  run_test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Installing buildpacks.io pack tool
        run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.15.1/pack-v0.15.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
      - name: Run test script
        run: ./scripts/test.sh
